In [114]:
import pandas as pd
import seaborn as sns
import numpy as np
import statsmodels.api as sm
import os
sns.set_theme()
from sklearn.preprocessing import LabelEncoder
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
cwd = os.getcwd()
print("Current working directory:", cwd)

# Change the working directory
#os.chdir('S:/OneDrive - University of Georgia/1 UGA/1 PhD/1 Spring24/Tobacco')
#os.chdir(r'/Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/1 Spring24/Tobacco')

os.chdir(r'/Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_Chapter/madeData')

# Verify the change
print("New working directory:", os.getcwd())

Current working directory: /Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_chapter/madeData
New working directory: /Users/sus/Library/CloudStorage/OneDrive-UniversityofGeorgia/1 UGA/1 PhD/Fall25/First_chapter/madeData

In [ ]:
# Loading the dataset
df = pd.read_excel('monthly_CPI.xlsx')

df # region week level

# Loading the dataset
df2 = pd.read_csv("FINAL_Chapter1.csv")

df

df2

,W,region,year,totrev_Smoke,qt_Smoke,totrev_Heat,qt_Heat,Laspeyres_Smoke,Paasche_Smoke,Fisher_Smoke,...,Laspeyres_Heat,Paasche_Heat,Fisher_Heat,Tornqvist_Heat,CPI,ln_CPI,weekly_percap_income,weekly_percap_exp,PopValue,IncValue
0,1,1,2017,2.574840e+06,5578.204,209494.044,414.742,0.960471,0.960322,0.960397,...,0.953496,0.953712,0.953604,0.976514,98.50,4.590057,23411.669105,15623.322767,7379369,22555163
1,1,2,2017,2.729862e+06,5567.702,150458.728,296.045,0.960350,0.960085,0.960218,...,0.953464,0.953793,0.953629,0.976555,97.50,4.579852,32965.644967,14137.930349,5325162,14862136
2,1,3,2017,1.046158e+06,2116.976,57934.923,112.455,0.960401,0.961194,0.960797,...,0.953484,0.953834,0.953659,0.976576,98.30,4.588024,22657.237490,17272.969612,2984997,9364325
3,1,4,2017,3.198163e+06,7037.711,213254.932,439.983,0.960328,0.960726,0.960527,...,0.953479,0.953793,0.953636,0.976555,98.00,4.584967,28318.976409,25697.525364,7652991,25612412
4,1,5,2017,1.337419e+07,29068.790,1035634.873,2102.634,0.960375,0.960989,0.960682,...,0.953481,0.953857,0.953669,0.976588,97.85,4.583436,25039.147976,20719.002146,36505374,151596974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2191,183,8,2020,4.984312e+05,1075.484,164780.339,336.905,1.042209,1.042764,1.042487,...,1.044072,1.029621,1.036822,1.015022,100.00,4.605170,43651.112290,33415.131712,1467480,3197328
2192,183,9,2020,1.348564e+06,2465.845,371034.720,680.921,1.042580,1.041026,1.041803,...,1.044160,1.029139,1.036622,1.014790,100.10,4.606170,87753.555561,40521.702895,3696171,9775360
2193,183,10,2020,1.347240e+06,2565.614,503146.661,950.301,1.042691,1.038873,1.040781,...,1.044087,1.027788,1.035905,1.014124,100.10,4.606170,74497.230566,50971.621417,4249283,11884910
2194,183,11,2020,3.096018e+06,6137.084,1330899.271,2506.863,1.042050,1.038753,1.040400,...,1.043995,1.026790,1.035357,1.013632,99.85,4.603669,64612.736910,35669.292833,8611195,23556619
2195,183,12,2020,4.644789e+06,8551.305,2057522.963,3654.706,1.042086,1.039866,1.040975,...,1.043923,1.026924,1.035389,1.013695,100.00,4.605170,113872.374167,60306.605335,14924613,48119227

In [107]:
# merging these two datasets for getting the other variables like price indices and monthly budget share and quantities

merged_df1 = pd.merge(df2, df, on=[ 'region', 'W'], how='inner')

merged_df1

,W,region,year,totrev_Smoke,qt_Smoke,totrev_Heat,qt_Heat,Laspeyres_Smoke,Paasche_Smoke,Fisher_Smoke,...,CPI_x,ln_CPI_x,weekly_percap_income,weekly_percap_exp,PopValue,IncValue,Area(2020-base),month,CPI_y,ln_CPI_y
0,1,1,2017,2.574840e+06,5578.204,209494.044,414.742,0.960471,0.960322,0.960397,...,98.50,4.590057,23411.669105,15623.322767,7379369,22555163,Chugoku districts,2017000101,98.50,4.590057
1,1,2,2017,2.729862e+06,5567.702,150458.728,296.045,0.960350,0.960085,0.960218,...,97.50,4.579852,32965.644967,14137.930349,5325162,14862136,Hokkaido districts,2017000101,97.50,4.579852
2,1,3,2017,1.046158e+06,2116.976,57934.923,112.455,0.960401,0.961194,0.960797,...,98.30,4.588024,22657.237490,17272.969612,2984997,9364325,Hokuriku districts,2017000101,98.30,4.588024
3,1,4,2017,3.198163e+06,7037.711,213254.932,439.983,0.960328,0.960726,0.960527,...,98.00,4.584967,28318.976409,25697.525364,7652991,25612412,Kanto districts,2017000101,98.00,4.584967
4,1,5,2017,1.337419e+07,29068.790,1035634.873,2102.634,0.960375,0.960989,0.960682,...,97.85,4.583436,25039.147976,20719.002146,36505374,151596974,Keihin district,2017000101,97.85,4.583436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2191,183,8,2020,4.984312e+05,1075.484,164780.339,336.905,1.042209,1.042764,1.042487,...,100.00,4.605170,43651.112290,33415.131712,1467480,3197328,Okinawa districts,2020000707,100.00,4.605170
2192,183,9,2020,1.348564e+06,2465.845,371034.720,680.921,1.042580,1.041026,1.041803,...,100.10,4.606170,87753.555561,40521.702895,3696171,9775360,Shikoku districts,2020000707,100.10,4.606170
2193,183,10,2020,1.347240e+06,2565.614,503146.661,950.301,1.042691,1.038873,1.040781,...,100.10,4.606170,74497.230566,50971.621417,4249283,11884910,Nagano-shi,2020000707,100.10,4.606170
2194,183,11,2020,3.096018e+06,6137.084,1330899.271,2506.863,1.042050,1.038753,1.040400,...,99.85,4.603669,64612.736910,35669.292833,8611195,23556619,Tohoku district,2020000707,99.85,4.603669
2195,183,12,2020,4.644789e+06,8551.305,2057522.963,3654.706,1.042086,1.039866,1.040975,...,100.00,4.605170,113872.374167,60306.605335,14924613,48119227,Tohoku districts,2018001010,100.30,4.608166

In [108]:
merged_df22 = merged_df1[['month', 'region', 'CPI_x', 'ln_CPI_x', 'totrev_Smoke', 'totrev_Heat', 'qt_Smoke', 'qt_Heat', 'Tornqvist_Smoke', 'Tornqvist_Heat', 'PopValue' ]]
merged_df22

,month,region,CPI_x,ln_CPI_x,totrev_Smoke,totrev_Heat,qt_Smoke,qt_Heat,Tornqvist_Smoke,Tornqvist_Heat,PopValue
0,2017000101,1,98.50,4.590057,2.574840e+06,209494.044,5578.204,414.742,0.979987,0.976514,7379369
1,2017000101,2,97.50,4.579852,2.729862e+06,150458.728,5567.702,296.045,0.979897,0.976555,5325162
2,2017000101,3,98.30,4.588024,1.046158e+06,57934.923,2116.976,112.455,0.980429,0.976576,2984997
3,2017000101,4,98.00,4.584967,3.198163e+06,213254.932,7037.711,439.983,0.980191,0.976555,7652991
4,2017000101,5,97.85,4.583436,1.337419e+07,1035634.873,29068.790,2102.634,0.980318,0.976588,36505374
...,...,...,...,...,...,...,...,...,...,...,...
2191,2020000707,8,100.00,4.605170,4.984312e+05,164780.339,1075.484,336.905,1.021484,1.015022,1467480
2192,2020000707,9,100.10,4.606170,1.348564e+06,371034.720,2465.845,680.921,1.020482,1.014790,3696171
2193,2020000707,10,100.10,4.606170,1.347240e+06,503146.661,2565.614,950.301,1.019431,1.014124,4249283
2194,2020000707,11,99.85,4.603669,3.096018e+06,1330899.271,6137.084,2506.863,1.019374,1.013632,8611195
2195,2018001010,12,100.00,4.605170,4.644789e+06,2057522.963,8551.305,3654.706,1.019914,1.013695,14924613

In [109]:
# 2. Aggregate to Monthly Level (Collapsing the data)
# We group by Region, Year, and Month to preserve the panel structure
monthly_df = merged_df22.groupby(['region', 'month']).agg({
    'totrev_Smoke': 'sum',         # Sum expenditures
    'totrev_Heat': 'sum',
    'qt_Smoke': 'sum',             # Sum quantities (packs)
    'qt_Heat': 'sum',   # Average income (Income flow is smooth)
    'Tornqvist_Smoke': 'mean',
    'Tornqvist_Heat': 'mean',
    'CPI_x': 'mean',
    'ln_CPI_x': 'mean',
    'PopValue': 'mean'                  # Average CPI (Price index is smooth)
}).reset_index()

In [110]:

monthly_df

,region,month,totrev_Smoke,totrev_Heat,qt_Smoke,qt_Heat,Tornqvist_Smoke,Tornqvist_Heat,CPI_x,ln_CPI_x,PopValue
0,1,2017000101,1.360154e+07,1135827.451,29321.760,2229.941,0.980054,0.976555,98.47600,4.589813,7379369.00
1,1,2017000202,1.084797e+07,1040669.061,23385.937,2084.185,0.980024,0.976580,98.32375,4.588266,7379369.00
2,1,2017000303,1.083315e+07,1112203.864,23291.136,2200.088,0.979915,0.976563,98.23750,4.587388,7379369.00
3,1,2017000404,1.355458e+07,1530679.843,29043.809,3062.408,0.981613,0.976561,98.48500,4.589904,7379369.00
4,1,2017000505,1.041131e+07,1282094.056,22482.665,2638.462,0.981496,0.976594,98.65000,4.591578,7379369.00
...,...,...,...,...,...,...,...,...,...,...,...
511,12,2020000303,2.412864e+07,9304397.375,46819.701,17495.835,1.020099,1.015591,99.90000,4.604170,14984722.00
512,12,2020000404,1.916688e+07,7844751.965,37191.856,14730.044,1.020057,1.015408,100.01500,4.605320,14939640.25
513,12,2020000505,1.844615e+07,7938043.608,35424.748,14666.271,1.019958,1.014508,100.38000,4.608961,14924613.00
514,12,2020000606,1.801111e+07,8067954.409,33796.344,14639.426,1.019974,1.014445,100.57500,4.610904,14924613.00
515,12,2020000707,9.123458e+06,4072080.549,16993.687,7385.336,1.019976,1.014133,100.60000,4.611152,14924613.00

In [111]:

# Loading the dataset
df22 = pd.read_excel("final_inc_exp.xlsx")


# We group by Region, Year, and Month to preserve the panel structure
monthly_df2 = df22.groupby(['region', 'month']).agg({
    'monthly_percap_exp': 'mean',         # Sum expenditures
    'monthly_percap_income': 'mean'                 # Average CPI (Price index is smooth)
}).reset_index()


monthly_df2

     region       month  monthly_percap_exp  monthly_percap_income
0         1  2017000101        87992.899408          117281.656805
1         1  2017000202        81163.204748          130547.774481
2         1  2017000303        93413.690476          113573.214286
3         1  2017000404        87307.418398          128986.350148
4         1  2017000505        90750.148368          108337.091988
..      ...         ...                 ...                    ...
511      12  2020000303       106407.674419          186927.751938
512      12  2020000404       100225.156250          179617.109375
513      12  2020000505        94012.736922          166550.568613
514      12  2020000606        88941.243366          321346.474602
515      12  2020000707        93044.081942          239705.159332

[516 rows x 4 columns]

In [112]:
# merge this with the monthly income or expenditure variables
merged_df = pd.merge(monthly_df, monthly_df2, on=[ 'region', 'month'], how='inner')

merged_df

,region,month,totrev_Smoke,totrev_Heat,qt_Smoke,qt_Heat,Tornqvist_Smoke,Tornqvist_Heat,CPI_x,ln_CPI_x,PopValue,monthly_percap_exp,monthly_percap_income
0,1,2017000101,1.360154e+07,1135827.451,29321.760,2229.941,0.980054,0.976555,98.47600,4.589813,7379369.00,87992.899408,117281.656805
1,1,2017000202,1.084797e+07,1040669.061,23385.937,2084.185,0.980024,0.976580,98.32375,4.588266,7379369.00,81163.204748,130547.774481
2,1,2017000303,1.083315e+07,1112203.864,23291.136,2200.088,0.979915,0.976563,98.23750,4.587388,7379369.00,93413.690476,113573.214286
3,1,2017000404,1.355458e+07,1530679.843,29043.809,3062.408,0.981613,0.976561,98.48500,4.589904,7379369.00,87307.418398,128986.350148
4,1,2017000505,1.041131e+07,1282094.056,22482.665,2638.462,0.981496,0.976594,98.65000,4.591578,7379369.00,90750.148368,108337.091988
...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,12,2020000303,2.412864e+07,9304397.375,46819.701,17495.835,1.020099,1.015591,99.90000,4.604170,14984722.00,106407.674419,186927.751938
512,12,2020000404,1.916688e+07,7844751.965,37191.856,14730.044,1.020057,1.015408,100.01500,4.605320,14939640.25,100225.156250,179617.109375
513,12,2020000505,1.844615e+07,7938043.608,35424.748,14666.271,1.019958,1.014508,100.38000,4.608961,14924613.00,94012.736922,166550.568613
514,12,2020000606,1.801111e+07,8067954.409,33796.344,14639.426,1.019974,1.014445,100.57500,4.610904,14924613.00,88941.243366,321346.474602
515,12,2020000707,9.123458e+06,4072080.549,16993.687,7385.336,1.019976,1.014133,100.60000,4.611152,14924613.00,93044.081942,239705.159332

In [113]:
merged_df.to_csv('monthly_firststage.csv', index=False )